/**
 * Shared paper-craft drawing primitives for PEELBEAST sprite authoring.
 *
 * Every sprite in `assets/source/sprites/` is generated from `sprite-sources.mjs`
 * using these helpers, then written out as a STANDALONE `.svg` file. Standalone
 * means an artist can open any single sprite in Inkscape/Illustrator, redraw it,
 * and the raster pipeline (`build-sprites.mjs`) will pick the change up without
 * touching the generator.
 *
 * The visual language is taken from the v0.8 reference sheet
 * (`assets/source/reference/legacy-atlas-v0.8.webp`):
 *   - warm cream paper, brown desk
 *   - kiss-cut stickers: a thick off-white border hugging the silhouette
 *   - hand-cut wobble on that border (never on the artwork itself)
 *   - soft drop shadow so pieces read as physically lying on the desk
 *   - painted gouache fills with a visible darker ink line
 */

export const PALETTE = {
  ink: '#3a2b1e',
  inkSoft: '#5d4632',
  paper: '#f4e8ce',
  paperLight: '#fbf4e2',
  paperDark: '#e3d3ae',
  cut: '#fdfaf1', // kiss-cut border colour
  desk: '#8a6242',
  deskDark: '#6b492f',

  furLight: '#c9d3dc',
  fur: '#8fa2b5',
  furDark: '#6d8298',
  belly: '#f3e8d2',

  crust: '#c08a4a',
  crustDark: '#a06e35',
  bread: '#f3e0b0',

  red: '#b4533b',
  redDark: '#8e3c28',
  blue: '#5b7396',
  blueDark: '#42566f',
  green: '#7e9166',
  greenDark: '#5f7049',
  gold: '#c4a05c',
  purple: '#8361a7',

  metal: '#c3c8cb',
  metalDark: '#8e979d',
  black: '#2e2a28',
  blackSoft: '#4a4441',
  white: '#fbf8f0',
};

/**
 * Kiss-cut sticker filter. Dilates the source alpha into an off-white backing,
 * wobbles that backing with fractal noise so the cut looks hand-made, and drops
 * a soft shadow beneath it.
 *
 * `feDropShadow` is deliberately avoided — librsvg (which sharp rasterises with)
 * has patchy support for it, so the shadow is built from primitives that are
 * safe in SVG 1.1.
 */
export function kissCutFilter({ id = 'kiss', radius = 7, wobble = 4, seed = 3, shadow = 0.3 } = {}) {
  return `
  <filter id="${id}" x="-30%" y="-30%" width="160%" height="170%" color-interpolation-filters="sRGB">
    <feTurbulence type="fractalNoise" baseFrequency="0.035" numOctaves="2" seed="${seed}" result="noise"/>
    <feDisplacementMap in="SourceAlpha" in2="noise" scale="${wobble}" xChannelSelector="R" yChannelSelector="G" result="wob"/>
    <feMorphology in="wob" operator="dilate" radius="${radius}" result="spread"/>
    <feFlood flood-color="${PALETTE.cut}" result="cutColor"/>
    <feComposite in="cutColor" in2="spread" operator="in" result="border"/>
    <feOffset in="spread" dx="0" dy="${Math.round(radius * 0.8)}" result="shOff"/>
    <feGaussianBlur in="shOff" stdDeviation="${radius * 0.9}" result="shBlur"/>
    <feFlood flood-color="#3a2517" flood-opacity="${shadow}" result="shColor"/>
    <feComposite in="shColor" in2="shBlur" operator="in" result="shadow"/>
    <feMerge>
      <feMergeNode in="shadow"/>
      <feMergeNode in="border"/>
      <feMergeNode in="SourceGraphic"/>
    </feMerge>
  </filter>`;
}

/** Paper grain overlay, applied as a multiplying rectangle clipped to a shape. */
export function grainFilter({ id = 'grain', freq = 0.9, seed = 7 } = {}) {
  return `
  <filter id="${id}" x="0%" y="0%" width="100%" height="100%" color-interpolation-filters="sRGB">
    <feTurbulence type="fractalNoise" baseFrequency="${freq}" numOctaves="3" seed="${seed}" result="n"/>
    <feColorMatrix in="n" type="saturate" values="0" result="g"/>
  </filter>`;
}

/**
 * Wrap authored artwork in a complete, standalone SVG document.
 * The artwork is drawn once; the filter supplies backing + shadow.
 */
export function spriteDoc({ width, height, body, defs = '', seed = 3, radius = 7, wobble = 4, grain = true, shadow = 0.3 }) {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- PEELBEAST sprite. Generated by scripts/sprite-sources.mjs; safe to hand-edit.
     Replace this file and run \`npm run assets:sprites\` to update the raster. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" width="${width}" height="${height}">
  <defs>
${kissCutFilter({ id: 'kiss', radius, wobble, seed, shadow })}
${grain ? grainFilter({ id: 'grain', seed: seed + 11 }) : ''}
${defs}
  </defs>
  <g filter="url(#kiss)">
${body}
  </g>
</svg>
`;
}

/** Artwork with no sticker backing (backgrounds, effects, UI plates). */
export function flatDoc({ width, height, body, defs = '' }) {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- PEELBEAST sprite. Generated by scripts/sprite-sources.mjs; safe to hand-edit. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" width="${width}" height="${height}">
  <defs>
${grainFilter({ id: 'grain', seed: 5 })}
${defs}
  </defs>
${body}
</svg>
`;
}

/** A painted shape: fill plus the characteristic soft ink line. */
export function paint(d, fill, { stroke = PALETTE.ink, w = 3.5, opacity = 1, extra = '' } = {}) {
  return `<path d="${d}" fill="${fill}" stroke="${stroke}" stroke-width="${w}" stroke-linejoin="round" stroke-linecap="round" opacity="${opacity}" ${extra}/>`;
}

/** Simple shading wash — a translucent darker shape with no outline. */
export function shade(d, fill = '#000', opacity = 0.12) {
  return `<path d="${d}" fill="${fill}" opacity="${opacity}"/>`;
}

export function circle(cx, cy, r, fill, { stroke = PALETTE.ink, w = 3.5, opacity = 1 } = {}) {
  return `<circle cx="${cx}" cy="${cy}" r="${r}" fill="${fill}" stroke="${stroke}" stroke-width="${w}" opacity="${opacity}"/>`;
}

export function ellipse(cx, cy, rx, ry, fill, { stroke = PALETTE.ink, w = 3.5, opacity = 1, rotate = 0 } = {}) {
  const t = rotate ? ` transform="rotate(${rotate} ${cx} ${cy})"` : '';
  return `<ellipse cx="${cx}" cy="${cy}" rx="${rx}" ry="${ry}" fill="${fill}" stroke="${stroke}" stroke-width="${w}" opacity="${opacity}"${t}/>`;
}

export function line(x1, y1, x2, y2, { stroke = PALETTE.ink, w = 3, cap = 'round', opacity = 1 } = {}) {
  return `<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${stroke}" stroke-width="${w}" stroke-linecap="${cap}" opacity="${opacity}"/>`;
}

/** Grain wash confined to a path — gives the flat gouache fills some tooth. */
export function grainOver(d, opacity = 0.16) {
  return `<g clip-path="url(#gclip)" opacity="${opacity}"><path d="${d}" fill="#fff" filter="url(#grain)"/></g>`;
}

/** A strip of masking tape, used to pin parts onto the beast. */
export function tape(x, y, w, h, rot, color = '#e8dcbd') {
  return `<g transform="rotate(${rot} ${x + w / 2} ${y + h / 2})">
    <rect x="${x}" y="${y}" width="${w}" height="${h}" fill="${color}" opacity="0.92" stroke="${PALETTE.inkSoft}" stroke-width="1.6" stroke-opacity="0.35"/>
    <rect x="${x}" y="${y}" width="${w}" height="${h * 0.32}" fill="#fff" opacity="0.35"/>
  </g>`;
}
