/**
 * THE ASSET CATALOG — single source of truth for every image in PEELBEAST.
 *
 * ── Replacing art ────────────────────────────────────────────────────────────
 * 1. Drop the new image into `public/assets/<category>/`.
 * 2. Point this entry's `file` at it and update `width` / `height`.
 * 3. Nudge `anchorX` / `anchorY` / `scale` / `rotation` in /dev/assets and paste
 *    the copied JSON back here.
 * 4. `npm run assets:validate` then `npm run assets:atlas`.
 * No component, stylesheet or engine file needs to change.
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * Anchoring model:
 *   A body declares `attach[slot]`, a normalised point on the BODY image.
 *   A part declares `anchorX/anchorY`, a normalised point on the PART image.
 *   Rendering pins the part's anchor onto the body's attach point, sizes the
 *   part to `scale x renderedBodyWidth`, and rotates it about the anchor.
 */

import type { AssetCatalog, AssetEntry } from './assetTypes';

const HAND_AUTHORED = {
  license: 'CC0-1.0 (authored for this repository)',
  source: 'scripts/sprite-sources.mjs — hand-authored SVG, drawn against the v0.8 reference sheet',
  status: 'placeholder' as const,
};

const LEGACY_REFERENCE = {
  license: 'Unknown — inherited from the v0.8 upload. Reference only, not shipped in game.',
  source: 'assets/source/reference/legacy-atlas-v0.8.webp (sliced by scripts/extract-reference.mjs)',
  status: 'reference' as const,
};

/** Reference crops that are genuinely readable; the rest of the sheet is dead. */
const REFERENCE_CROPS: Array<[string, string, string]> = [
  ['ref.stage', 'Stage screenshot', 'stage_bg_base'],
  ['ref.hero_card', 'Hero card', 'hero_full'],
  ['ref.enemy_rat', 'Pencil Rat', 'enemy_pencil_rat'],
  ['ref.enemy_spider', 'Tape Spider', 'enemy_tape_spider'],
  ['ref.enemy_crow', 'Scissor Crow', 'enemy_scissor_crow'],
  ['ref.toast', 'Toast head crop', 'part_toast'],
  ['ref.scissors', 'Scissors crop', 'part_scissors'],
  ['ref.umbrella', 'Umbrella crop', 'part_umbrella'],
  ['ref.spear', 'Pencil spear crop', 'part_spear'],
  ['ref.bomb', 'Bomb belly crop', 'part_bomb'],
  ['ref.coffee', 'Coffee mug crop', 'part_coffee'],
  ['ref.tape', 'Tape roll crop', 'part_tape_roll'],
  ['ref.ribbon', 'Ribbon crop', 'part_ribbon'],
  ['ref.eye', 'Eye sticker crop', 'part_eye_sticker'],
  ['ref.ghost', 'Ghost charm crop', 'part_ghost_charm'],
  ['ref.patchbread', 'Bread patch crop', 'part_patchbread'],
  ['ref.boxshell', 'Box shell crop', 'part_box_shell'],
  ['ref.pencilcup', 'Pencil cup prop', 'prop_pencilcup_left'],
  ['ref.holdcard', 'Press-to-hold UI', 'prop_hold_card'],
];

function entry(e: AssetEntry): AssetEntry {
  return e;
}

export const ASSET_CATALOG: AssetCatalog = {
  // ── BODY ───────────────────────────────────────────────────────────────────
  'body.cat': entry({
    id: 'body.cat',
    displayName: 'Peelbeast Cat',
    category: 'body',
    file: '/assets/bodies/cat.png',
    fallbackFile: '/assets/placeholders/body.png',
    referenceFile: '/assets/references/hero_full.png',
    width: 800,
    height: 940,
    anchorX: 0.5,
    anchorY: 1.0,
    scale: 1,
    rotation: 0,
    zIndex: 20,
    attach: {
      head: { x: 0.5, y: 0.4 },
      hand: { x: 0.855, y: 0.515 },
      core: { x: 0.5, y: 0.7 },
      trinket: { x: 0.5, y: 0.475 },
    },
    animationProfile: 'soft-bounce',
    visualBounds: { x: 0.1, y: 0.32, w: 0.8, h: 0.62 },
    tags: ['player', 'cat', 'paper'],
    ...HAND_AUTHORED,
  }),

  /**
   * Recovered from the v0.8 reference sheet by scripts/build-reference-cutouts.mjs
   * — a real alpha cutout of the original painted sticker, not a redraw.
   */
  'art.hero_card': entry({
    id: 'art.hero_card',
    displayName: 'Peelbeast (original sticker)',
    category: 'art',
    file: '/assets/bodies/hero_card_ref.png',
    fallbackFile: '/assets/bodies/cat.png',
    referenceFile: '/assets/references/hero_full.png',
    width: 720,
    height: 745,
    anchorX: 0.5,
    anchorY: 1,
    scale: 1,
    rotation: 0,
    zIndex: 20,
    animationProfile: 'soft-bounce',
    tags: ['player', 'reference-derived', 'painted'],
    license: 'Unknown — inherited from the v0.8 upload.',
    source: 'assets/source/reference/legacy-atlas-v0.8.webp, background removed by scripts/build-reference-cutouts.mjs',
    status: 'production',
  }),

  // ── HEAD PARTS ─────────────────────────────────────────────────────────────
  'part.head.toast_helm': entry({
    id: 'part.head.toast_helm',
    displayName: 'Toast Helm',
    category: 'part',
    slot: 'head',
    file: '/assets/parts/head/toast_helm.png',
    fallbackFile: '/assets/placeholders/head.png',
    referenceFile: '/assets/references/part_toast.png',
    width: 496,
    height: 464,
    anchorX: 0.5,
    anchorY: 0.9,
    scale: 0.46,
    rotation: -5,
    zIndex: 30,
    bodyCompatibility: ['body.cat'],
    animationProfile: 'soft-bounce',
    tags: ['bread', 'warm', 'focus'],
    ...HAND_AUTHORED,
  }),
  'part.head.box_shell': entry({
    id: 'part.head.box_shell',
    displayName: 'Box Shell',
    category: 'part',
    slot: 'head',
    file: '/assets/parts/head/box_shell.png',
    fallbackFile: '/assets/placeholders/head.png',
    referenceFile: '/assets/references/part_box_shell.png',
    width: 472,
    height: 448,
    anchorX: 0.5,
    anchorY: 0.94,
    scale: 0.46,
    rotation: -3,
    zIndex: 30,
    bodyCompatibility: ['body.cat'],
    animationProfile: 'static',
    tags: ['cardboard', 'guard', 'bulk'],
    ...HAND_AUTHORED,
  }),
  'part.head.ghost_hood': entry({
    id: 'part.head.ghost_hood',
    displayName: 'Ghost Hood',
    category: 'part',
    slot: 'head',
    file: '/assets/parts/head/ghost_hood.png',
    fallbackFile: '/assets/placeholders/head.png',
    referenceFile: '/assets/references/part_ghost_charm.png',
    width: 424,
    height: 468,
    anchorX: 0.5,
    anchorY: 0.88,
    scale: 0.4,
    rotation: 2,
    zIndex: 30,
    bodyCompatibility: ['body.cat'],
    animationProfile: 'float',
    tags: ['ghost', 'drift', 'light'],
    ...HAND_AUTHORED,
  }),

  // ── HAND PARTS ─────────────────────────────────────────────────────────────
  'part.hand.scissors': entry({
    id: 'part.hand.scissors',
    displayName: 'Scissors',
    category: 'part',
    slot: 'hand',
    file: '/assets/parts/hand/scissors.png',
    fallbackFile: '/assets/placeholders/hand.png',
    referenceFile: '/assets/references/part_scissors.png',
    width: 492,
    height: 524,
    anchorX: 0.5,
    anchorY: 0.78,
    scale: 0.36,
    rotation: 12,
    zIndex: 40,
    bodyCompatibility: ['body.cat'],
    animationProfile: 'jitter',
    tags: ['blade', 'cut', 'red'],
    ...HAND_AUTHORED,
  }),
  'part.hand.pencil_spear': entry({
    id: 'part.hand.pencil_spear',
    displayName: 'Pencil Spear',
    category: 'part',
    slot: 'hand',
    file: '/assets/parts/hand/pencil_spear.png',
    fallbackFile: '/assets/placeholders/hand.png',
    referenceFile: '/assets/references/part_spear.png',
    width: 288,
    height: 624,
    anchorX: 0.5,
    anchorY: 0.62,
    scale: 0.17,
    rotation: 16,
    zIndex: 40,
    bodyCompatibility: ['body.cat'],
    animationProfile: 'static',
    tags: ['pierce', 'pin', 'graphite'],
    ...HAND_AUTHORED,
  }),
  'part.hand.umbrella_hook': entry({
    id: 'part.hand.umbrella_hook',
    displayName: 'Umbrella Hook',
    category: 'part',
    slot: 'hand',
    file: '/assets/parts/hand/umbrella_hook.png',
    fallbackFile: '/assets/placeholders/hand.png',
    referenceFile: '/assets/references/part_umbrella.png',
    width: 524,
    height: 548,
    anchorX: 0.36,
    anchorY: 0.82,
    scale: 0.44,
    rotation: -6,
    zIndex: 40,
    bodyCompatibility: ['body.cat'],
    animationProfile: 'sway',
    tags: ['shelter', 'ink', 'block'],
    ...HAND_AUTHORED,
  }),

  // ── CORE PARTS ─────────────────────────────────────────────────────────────
  'part.core.bomb_belly': entry({
    id: 'part.core.bomb_belly',
    displayName: 'Bomb Belly',
    category: 'part',
    slot: 'core',
    file: '/assets/parts/core/bomb_belly.png',
    fallbackFile: '/assets/placeholders/core.png',
    referenceFile: '/assets/references/part_bomb.png',
    width: 428,
    height: 428,
    anchorX: 0.49,
    anchorY: 0.55,
    scale: 0.34,
    rotation: 0,
    zIndex: 26,
    bodyCompatibility: ['body.cat'],
    animationProfile: 'jitter',
    tags: ['burst', 'volatile', 'black'],
    ...HAND_AUTHORED,
  }),
  'part.core.coffee_cup': entry({
    id: 'part.core.coffee_cup',
    displayName: 'Coffee Cup',
    category: 'part',
    slot: 'core',
    file: '/assets/parts/core/coffee_cup.png',
    fallbackFile: '/assets/placeholders/core.png',
    referenceFile: '/assets/references/part_coffee.png',
    width: 448,
    height: 388,
    anchorX: 0.44,
    anchorY: 0.55,
    scale: 0.32,
    rotation: 4,
    zIndex: 26,
    bodyCompatibility: ['body.cat'],
    animationProfile: 'soft-bounce',
    tags: ['glue', 'haste', 'warm'],
    ...HAND_AUTHORED,
  }),
  'part.core.tape_roll': entry({
    id: 'part.core.tape_roll',
    displayName: 'Tape Roll',
    category: 'part',
    slot: 'core',
    file: '/assets/parts/core/tape_roll.png',
    fallbackFile: '/assets/placeholders/core.png',
    referenceFile: '/assets/references/part_tape_roll.png',
    width: 432,
    height: 404,
    anchorX: 0.48,
    anchorY: 0.52,
    scale: 0.32,
    rotation: -6,
    zIndex: 26,
    bodyCompatibility: ['body.cat'],
    animationProfile: 'spin-slow',
    tags: ['repair', 'adhesive', 'reattach'],
    ...HAND_AUTHORED,
  }),

  // ── TRINKET PARTS ──────────────────────────────────────────────────────────
  'part.trinket.ribbon_knot': entry({
    id: 'part.trinket.ribbon_knot',
    displayName: 'Ribbon Knot',
    category: 'part',
    slot: 'trinket',
    file: '/assets/parts/trinket/ribbon_knot.png',
    fallbackFile: '/assets/placeholders/trinket.png',
    referenceFile: '/assets/references/part_ribbon.png',
    width: 468,
    height: 324,
    anchorX: 0.5,
    anchorY: 0.5,
    scale: 0.3,
    rotation: -4,
    zIndex: 34,
    bodyCompatibility: ['body.cat'],
    animationProfile: 'sway',
    tags: ['speed', 'drift', 'red'],
    ...HAND_AUTHORED,
  }),
  'part.trinket.eye_sticker': entry({
    id: 'part.trinket.eye_sticker',
    displayName: 'Eye Sticker',
    category: 'part',
    slot: 'trinket',
    file: '/assets/parts/trinket/eye_sticker.png',
    fallbackFile: '/assets/placeholders/trinket.png',
    referenceFile: '/assets/references/part_eye_sticker.png',
    width: 344,
    height: 344,
    anchorX: 0.5,
    anchorY: 0.5,
    scale: 0.19,
    rotation: 8,
    zIndex: 34,
    bodyCompatibility: ['body.cat'],
    animationProfile: 'jitter',
    tags: ['insight', 'foresee', 'sticker'],
    ...HAND_AUTHORED,
  }),
  'part.trinket.bread_patch': entry({
    id: 'part.trinket.bread_patch',
    displayName: 'Bread Patch',
    category: 'part',
    slot: 'trinket',
    file: '/assets/parts/trinket/bread_patch.png',
    fallbackFile: '/assets/placeholders/trinket.png',
    referenceFile: '/assets/references/part_patchbread.png',
    width: 448,
    height: 312,
    anchorX: 0.5,
    anchorY: 0.5,
    scale: 0.24,
    rotation: -8,
    zIndex: 34,
    bodyCompatibility: ['body.cat'],
    animationProfile: 'soft-bounce',
    tags: ['mend', 'heal', 'bread'],
    ...HAND_AUTHORED,
  }),

  // ── ENEMIES ────────────────────────────────────────────────────────────────
  'enemy.pencil_rat': entry({
    id: 'enemy.pencil_rat',
    displayName: 'Pencil Rat',
    category: 'enemy',
    file: '/assets/enemies/pencil_rat.png',
    fallbackFile: '/assets/placeholders/enemy.png',
    referenceFile: '/assets/references/enemy_pencil_rat.png',
    width: 660,
    height: 680,
    anchorX: 0.5,
    anchorY: 1,
    scale: 1,
    rotation: 0,
    zIndex: 20,
    animationProfile: 'jitter',
    visualBounds: { x: 0.12, y: 0.1, w: 0.72, h: 0.85 },
    tags: ['scavenger', 'glue-thief'],
    ...HAND_AUTHORED,
  }),
  'enemy.tape_spider': entry({
    id: 'enemy.tape_spider',
    displayName: 'Tape Spider',
    category: 'enemy',
    file: '/assets/enemies/tape_spider.png',
    fallbackFile: '/assets/placeholders/enemy.png',
    referenceFile: '/assets/references/enemy_tape_spider.png',
    width: 732,
    height: 600,
    anchorX: 0.5,
    anchorY: 1,
    scale: 1,
    rotation: 0,
    zIndex: 20,
    animationProfile: 'sway',
    visualBounds: { x: 0.14, y: 0.1, w: 0.72, h: 0.82 },
    tags: ['bind', 'ink', 'nest'],
    ...HAND_AUTHORED,
  }),
  'enemy.scissor_crow': entry({
    id: 'enemy.scissor_crow',
    displayName: 'Scissor Crow',
    category: 'enemy',
    file: '/assets/enemies/scissor_crow.png',
    fallbackFile: '/assets/placeholders/enemy.png',
    referenceFile: '/assets/references/enemy_scissor_crow.png',
    width: 684,
    height: 644,
    anchorX: 0.5,
    anchorY: 1,
    scale: 1,
    rotation: 0,
    zIndex: 20,
    animationProfile: 'soft-bounce',
    visualBounds: { x: 0.12, y: 0.08, w: 0.76, h: 0.86 },
    tags: ['elite', 'peel', 'raider'],
    ...HAND_AUTHORED,
  }),
  'enemy.clip_moth': entry({
    id: 'enemy.clip_moth',
    displayName: 'Clip Moth',
    category: 'enemy',
    file: '/assets/enemies/clip_moth.png',
    fallbackFile: '/assets/placeholders/enemy.png',
    width: 640,
    height: 524,
    anchorX: 0.5,
    anchorY: 1,
    scale: 1,
    rotation: 0,
    zIndex: 20,
    animationProfile: 'float',
    visualBounds: { x: 0.08, y: 0.14, w: 0.84, h: 0.72 },
    tags: ['frazzle', 'dust', 'flier'],
    ...HAND_AUTHORED,
  }),

  // ── BACKGROUNDS ────────────────────────────────────────────────────────────
  'bg.desk': entry({
    id: 'bg.desk',
    displayName: 'Desk & Notebook',
    category: 'background',
    file: '/assets/backgrounds/desk.png',
    fallbackFile: '/assets/placeholders/generic.png',
    referenceFile: '/assets/references/stage_bg_base.png',
    width: 1600,
    height: 900,
    anchorX: 0.5,
    anchorY: 0.5,
    scale: 1,
    rotation: 0,
    zIndex: 0,
    animationProfile: 'static',
    tags: ['stage', 'paper'],
    ...HAND_AUTHORED,
  }),
  'bg.nest': entry({
    id: 'bg.nest',
    displayName: 'Draftboard Nest',
    category: 'background',
    file: '/assets/backgrounds/nest.png',
    fallbackFile: '/assets/backgrounds/desk.png',
    referenceFile: '/assets/references/stage_bg_base.png',
    width: 1600,
    height: 900,
    anchorX: 0.5,
    anchorY: 0.5,
    scale: 1,
    rotation: 0,
    zIndex: 0,
    animationProfile: 'static',
    tags: ['stage', 'boss', 'web'],
    ...HAND_AUTHORED,
  }),

  // ── PROPS ──────────────────────────────────────────────────────────────────
  'prop.pencil_cup': entry({
    id: 'prop.pencil_cup',
    displayName: 'Pencil Cup',
    category: 'prop',
    file: '/assets/props/pencil_cup.png',
    fallbackFile: '/assets/placeholders/generic.png',
    referenceFile: '/assets/references/prop_pencilcup_left.png',
    width: 336,
    height: 576,
    anchorX: 0.5,
    anchorY: 1,
    scale: 1,
    rotation: -3,
    zIndex: 10,
    animationProfile: 'static',
    tags: ['desk'],
    ...HAND_AUTHORED,
  }),
  'prop.torn_note': entry({
    id: 'prop.torn_note',
    displayName: 'Torn Note',
    category: 'prop',
    file: '/assets/props/torn_note.png',
    fallbackFile: '/assets/placeholders/generic.png',
    referenceFile: '/assets/references/prop_tornpaper_right.png',
    width: 472,
    height: 548,
    anchorX: 0.5,
    anchorY: 0.5,
    scale: 1,
    rotation: 6,
    zIndex: 10,
    animationProfile: 'static',
    tags: ['desk'],
    ...HAND_AUTHORED,
  }),
  'prop.clip_pile': entry({
    id: 'prop.clip_pile',
    displayName: 'Clip Pile',
    category: 'prop',
    file: '/assets/props/clip_pile.png',
    fallbackFile: '/assets/placeholders/generic.png',
    width: 488,
    height: 312,
    anchorX: 0.5,
    anchorY: 1,
    scale: 1,
    rotation: 0,
    zIndex: 10,
    animationProfile: 'static',
    tags: ['desk'],
    ...HAND_AUTHORED,
  }),
  'prop.tape_dispenser': entry({
    id: 'prop.tape_dispenser',
    displayName: 'Tape Dispenser',
    category: 'prop',
    file: '/assets/props/tape_dispenser.png',
    fallbackFile: '/assets/placeholders/generic.png',
    width: 512,
    height: 380,
    anchorX: 0.5,
    anchorY: 1,
    scale: 1,
    rotation: -2,
    zIndex: 10,
    animationProfile: 'static',
    tags: ['desk', 'shop'],
    ...HAND_AUTHORED,
  }),

  // ── UI DECORATION ──────────────────────────────────────────────────────────
  'ui.clip': entry({
    id: 'ui.clip',
    displayName: 'Paper Clip',
    category: 'ui',
    file: '/assets/ui/clip.png',
    fallbackFile: '/assets/placeholders/generic.png',
    width: 240,
    height: 380,
    anchorX: 0.5,
    anchorY: 0.5,
    scale: 1,
    rotation: 0,
    zIndex: 60,
    animationProfile: 'static',
    tags: ['decor'],
    ...HAND_AUTHORED,
  }),
  'ui.tape_strip': entry({
    id: 'ui.tape_strip',
    displayName: 'Tape Strip',
    category: 'ui',
    file: '/assets/ui/tape_strip.png',
    fallbackFile: '/assets/placeholders/generic.png',
    width: 480,
    height: 180,
    anchorX: 0.5,
    anchorY: 0.5,
    scale: 1,
    rotation: 0,
    zIndex: 60,
    animationProfile: 'static',
    tags: ['decor'],
    ...HAND_AUTHORED,
  }),
  'ui.tag': entry({
    id: 'ui.tag',
    displayName: 'Paper Tag',
    category: 'ui',
    file: '/assets/ui/tag.png',
    fallbackFile: '/assets/placeholders/generic.png',
    referenceFile: '/assets/references/prop_hold_card.png',
    width: 520,
    height: 260,
    anchorX: 0.5,
    anchorY: 0.5,
    scale: 1,
    rotation: 0,
    zIndex: 60,
    animationProfile: 'static',
    tags: ['decor'],
    ...HAND_AUTHORED,
  }),

  // ── STATUS ICONS ───────────────────────────────────────────────────────────
  ...Object.fromEntries(
    (
      [
        ['focus', 'Focus'],
        ['drift', 'Drift'],
        ['bind', 'Bind'],
        ['haste', 'Haste'],
        ['pinned', 'Pinned'],
        ['fragile', 'Fragile'],
        ['frazzle', 'Frazzle'],
        ['ink', 'Ink Tide'],
        ['block', 'Block'],
        ['glue', 'Glue'],
        ['peel', 'Peel'],
      ] as const
    ).map(([key, name]) => [
      `icon.status.${key}`,
      entry({
        id: `icon.status.${key}`,
        displayName: `${name} icon`,
        category: 'icon',
        file: `/assets/ui/status_${key}.png`,
        fallbackFile: '/assets/placeholders/generic.png',
        width: 192,
        height: 192,
        anchorX: 0.5,
        anchorY: 0.5,
        scale: 1,
        rotation: 0,
        zIndex: 50,
        animationProfile: 'static',
        tags: ['status', key],
        ...HAND_AUTHORED,
      }),
    ]),
  ),

  // ── EFFECTS ────────────────────────────────────────────────────────────────
  ...Object.fromEntries(
    (
      [
        ['scrap', 'Paper Scrap', 184, 152],
        ['slash', 'Slash Arc', 360, 225],
        ['spark', 'Spark', 360, 360],
        ['impact', 'Impact Burst', 360, 360],
        ['patch', 'Patch Strip', 360, 225],
      ] as const
    ).map(([key, name, w, h]) => [
      `fx.${key}`,
      entry({
        id: `fx.${key}`,
        displayName: name,
        category: 'effect',
        file: `/assets/effects/${key}.png`,
        fallbackFile: '/assets/placeholders/generic.png',
        width: w,
        height: h,
        anchorX: 0.5,
        anchorY: 0.5,
        scale: 1,
        rotation: 0,
        zIndex: 70,
        animationProfile: 'static',
        tags: ['effect', key],
        ...HAND_AUTHORED,
      }),
    ]),
  ),

  // ── PLACEHOLDERS (must always resolve; they are the fallback of last resort) ─
  ...Object.fromEntries(
    (
      [
        ['head', 'Head placeholder', 480, 440],
        ['hand', 'Hand placeholder', 440, 520],
        ['core', 'Core placeholder', 420, 400],
        ['trinket', 'Trinket placeholder', 460, 300],
        ['body', 'Body placeholder', 800, 940],
        ['enemy', 'Enemy placeholder', 640, 640],
        ['generic', 'Generic placeholder', 400, 400],
      ] as const
    ).map(([key, name, w, h]) => [
      `ph.${key}`,
      entry({
        id: `ph.${key}`,
        displayName: name,
        category: 'placeholder',
        file: `/assets/placeholders/${key}.png`,
        width: w,
        height: h,
        anchorX: 0.5,
        anchorY: key === 'body' ? 1 : 0.5,
        scale: 1,
        rotation: 0,
        zIndex: 20,
        animationProfile: 'static',
        tags: ['placeholder'],
        ...HAND_AUTHORED,
      }),
    ]),
  ),

  // ── REFERENCE CROPS (never rendered as gameplay art) ───────────────────────
  ...Object.fromEntries(
    REFERENCE_CROPS.map(([id, name, fileBase]) => [
      id,
      entry({
        id,
        displayName: `Reference — ${name}`,
        category: 'reference',
        file: `/assets/references/${fileBase}.png`,
        width: 0,
        height: 0,
        anchorX: 0.5,
        anchorY: 0.5,
        scale: 1,
        rotation: 0,
        zIndex: 0,
        animationProfile: 'static',
        tags: ['reference', 'v0.8'],
        ...LEGACY_REFERENCE,
      }),
    ]),
  ),
};

export const ASSET_IDS = Object.keys(ASSET_CATALOG);
